# Generated by Django 4.0.1 on 2022-01-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='request_id',
            field=models.CharField(blank=True, help_text='An ID for the request that is generating the event. Usually passed around to track events related to a request', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_info',
            field=models.CharField(blank=True, help_text='Additional information about the service that is generating the event', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_name',
            field=models.CharField(blank=True, help_text='The name of the service that is generating the event', max_length=255),
        ),
    ]
