# Generated by Django 4.0.1 on 2022-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_uuid_alter_event_event_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='instance_id',
            field=models.CharField(blank=True, help_text='Unique ID for the service instance incase the service is distributed', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='request_id',
            field=models.CharField(blank=True, help_text='An ID for the request that is generating the event. Usually passed around to track events related to a request', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_info',
            field=models.CharField(blank=True, help_text='Additional information about the service that is generating the event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='service_name',
            field=models.CharField(blank=True, help_text='The name of the service that is generating the event', max_length=255, null=True),
        ),
    ]
